Repository nextflow-io/training, pull requests merged in 2025-06, with the labels that each got.

#596 CI: Validate headings
  .github/check_headings.py
  .github/workflows/check-headings.yml
  README.md
Labels: documentation, deployment

#618 Bump NXF_VER to latest stable (25.04.3)
  .devcontainer/codespaces-dev/devcontainer.json
  .devcontainer/devcontainer.json
  .devcontainer/local-dev/devcontainer.json
  .github/workflows/docker-devcontainer.yml
Labels: bug

#621 Minor link fixes
  docs/index.ko.md
  docs/index.md
Labels: bug

#622 Update French translation for the home page
  docs/help.fr.md
  docs/help.md
  docs/index.fr.md
  mkdocs.yml
Labels: documentation, Translations

#623 Fix buildx error when image contains attestation manifest
  .github/workflows/docker-devcontainer.yml
Labels: bug
